import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "node:path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    css: false,
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    exclude: ["node_modules", ".next", "dist", "e2e/**"],
    coverage: {
      provider: "v8",
      all: true,
      include: [
        "src/lib/api.ts",
        "src/lib/auth.tsx",
        "src/lib/profileCompleteness.ts",
        "src/lib/tier-display.ts",
        "src/lib/tier-gating.ts",
        "src/lib/tier-config.ts",
        "src/lib/phone.ts",
        "src/lib/applyLink.ts",
        "src/lib/jobDescription.ts",
        "src/lib/jobSource.ts",
        "src/lib/matchBreakdown.ts",
        "src/lib/matchExplanationDisplay.ts",
        "src/lib/formatMatchRelativeTime.ts",
        "src/lib/pushNotifications.ts",
        "src/lib/site-metadata.ts",
        "src/lib/utils.ts",
        "src/lib/trackApplyClick.ts",
        "src/components/auth/**/*.{ts,tsx}",
        "src/app/settings/_sections/AccountSection.tsx",
        "src/app/settings/_sections/NotificationsSection.tsx",
        "src/app/settings/_sections/BillingSection.tsx",
        "src/app/profile/ProfileCompletenessChecklist.tsx",
      ],
      reporter: ["text", "json-summary", "html"],
      exclude: [
        "**/*.test.{ts,tsx}",
        "src/**/__tests__/**",
        "**/*.d.ts",
        ".next/**",
        "node_modules/**",
        "src/test/**",
        "**/*.config.*",
        "src/app/**/layout.tsx",
        "src/app/**/loading.tsx",
        "src/app/**/error.tsx",
        "src/app/**/not-found.tsx",
      ],
      thresholds: {
        lines: 60,
        functions: 55,
        branches: 50,
        statements: 60,
      },
    },
  },
  resolve: {
    alias: { "@": path.resolve(__dirname, "./src") },
  },
});
